name: start-tasks
on: [workflow_dispatch]
jobs:
  testing-application:
    runs-on: ubuntu-latest
    steps: 
      - name: get repo
        uses: actions/checkout@v3
      - name: install dep
        run: npm i
      - name: greeting
        run: echo hallo!
