name: ci
on: [push, workflow_dispatch]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v3
      - name: install dep
        run: yarn install
      - name: storybook test
        run: npm run loki:ci